### ISSUE TITLE
Rate Limit Exceeded

### ISSUE THREAD

**Issue by tstanley17** [rohit-purandare/ShelfBridge#8]
When restarting after changing the config.yaml file, I cannot seem to get past this in my logs. 

shelfbridge    | 01:48:07 [warn]: Rate limit warning: 1073/600 requests used in the current minute service="shelfbridge" version="1.7.1" identifier="default" remainingRequests=0 resetTime="2025-07-15T01:49:05.329Z"

**Comment by unsubscrieb** [comment]
I got this issue as well, after ~10mins it eventually said first sync was a success. However, upon container restart, I am getting rate limit exceeded warnings again
```
01:57:04 [warn]: Rate limit warning: 742/600 requests used in the current minute service="shelfbridge" version="1.7.1" identifier="default" remainingRequests=0 resetTime="2025-07-15T01:58:04.054Z"
01:57:04 [warn]: Rate limit exceeded. Waiting 60s before next request service="shelfbridge" version="1.7.1" identifier="default" remainingRequests=0 resetTime="2025-07-15T01:58:04.054Z"
01:57:04 [warn]: Rate limit warning: 743/600 requests used in the current minute service="shelfbridge" version="1.7.1" identifier="default" remainingRequests=0 resetTime="2025-07-15T01:58:04.054Z"
01:57:04 [warn]: Rate limit exceeded. Waiting 60s before next request service="shelfbridge" version="1.7.1" identifier="default" remainingRequests=0 resetTime="2025-07-15T01:58:04.054Z"
```

**Comment by rohit-purandare** [comment]
Thank you for testing! I made a few tweaks to try to resolve, but my internet was hit by a storm on the east coast. Once it is back (hopefully tomorrow morning), I'll investigate further.

**Comment by ucrbuffalo** [comment]
Mine is still doing this as well. I just updated and tested it.
```
19:41:05 [warn]: Rate limit warning: 1065/600 requests used in the current minute service="shelfbridge" version="1.8.3" identifier="audiobookshelf" remainingRequests=0 resetTime="2025-07-15T19:41:44.221Z"
19:41:05 [warn]: Rate limit exceeded. Waiting 39s before next request service="shelfbridge" version="1.8.3" identifier="audiobookshelf" remainingRequests=0 resetTime="2025-07-15T19:41:44.220Z"
⏳ Rate limit reached. Waiting 39s before continuing...
```

My ABS has 396 books. (I'm gonna read them someday, I swear! 😅

**Comment by rohit-purandare** [comment]
@ucrbuffalo I only have about 100 so, so this is all super helpful feedback!

OK, actually @nealhead the logs you provided are very helpful. What I think may be happening is different workers are hitting the limit and not telling other workers that they are hitting the limit. That's why even after it says rate limit reached waiting, more keep being tried and being told to wait. I just pushed another change to implement a semaphore for both audiobookshelf and hardcover that should help control this. It is configurable, but defaults to 1 (which is safest). This is in latest / v1.9.2

Let me know once you get a chance to test and appreciate the patience on this! And if you run into more issues logs are always helpful!

**Comment by rohit-purandare** [comment]
From what another user told I also implemented a max_books_to_process option for the config. It is infinite by default, but you can set it to lower for testing

**Comment by unsubscrieb** [comment]
My ABS library is 484 books, 16 finished and 1 in progress. I set 1 worker and parallel off, latest update has no rate limit warnings!

**Comment by rohit-purandare** [comment]
@unsubscrieb Let's go! Keep me updated on how it goes!

**Comment by ucrbuffalo** [comment]
Well it took a while longer this time, but I am still getting the rate limit warnings.
```
02:09:26 [warn]: Rate limit exceeded. Waiting 55s before next request service="shelfbridge" version="1.11.0" identifier="audiobookshelf" remainingRequests=0 resetTime="2025-07-16T02:10:21.388Z"
⏳ Rate limit reached for 'audiobookshelf' (600/min). Waiting 55s before continuing...
```

**Comment by ucrbuffalo** [comment]
TBH, I'm not sure how to download the logs. I'm on Docker Desktop. I'll do some googling.

**Comment by ucrbuffalo** [comment]
Here's the log from my most recent run. Looks like it did successfully sync, but still attempted a lot of calls to the API after I had reached the limit, which could eventually cause issues from Hardcover's team.

https://pastebin.com/4Vaj2iYQ

**Comment by tstanley17** [comment]
Thanks! After repulling, it looks to resolve this issue for me. Books are now processing.

**Comment by ucrbuffalo** [comment]
Just updated my install and ran it again. It took a LONG time to process (probably because of those rate limits) and start showing progress. But eventually it did sync.

That said, it did some stuff that I'm not sure was (strictly speaking) correct. It added the wrong edition to Hardcover (added books instead of audiobooks), and marked one book as currently reading at 0% that I've never started. It also reset my progress on a book I'm currently reading, but that's my own fault because I have several copies of that book (I was looking for a version I could stomach).
